### PR TITLE
Draft: adding version API to all bindings

### PR DESCRIPTION
**Pull request by s0l0ist**
This PR attempts to add a centralized version API across all bindings.

There is a minor change to how JavaScript APIs are now initialized. Ex:

Previously, each client/server factory was async because the emscripten module needed to finish initializing:
```javascript
import PSI from '@openmined/psi.js'
// ...
const server = await PSI.server.createWithNewKey()
``` 

Now, the async initializer has been pulled out for better clarity in all PSI objects so that there is no `await`ing on any constructors/factories/static classes:
```javascript
import PSI from '@openmined/psi.js'
// ...
const psi = await PSI()
const server = psi.server.createWithNewKey()

// Version API
const { version }  = psi.package
console.log('version:', version)
```

- [x] CPP version API
- [x] C version API
- [x] JavaScript version API
- [x] Go version API
- ~~[ ] Python version API~~

### CODE REVIEW

**Comment by schoppmp** [comment]
I went over the C++ parts, they look good.

How do you plan to update the version in package.json? Should that be done manually or do you have a better idea?

**Comment by willclarktech** [comment]
> How do you plan to update the version in package.json? Should that be done manually or do you have a better idea?

We can maybe use `npm version [major|minor|patch]` in our publish script.

**Comment by s0l0ist** [comment]
@willclarktech glad you pointed this out. We would need to scrape the file in `tools/package.bzl` that contains the version string that all builds should reference.

**Comment by s0l0ist** [comment]
Python is a bit behind, merging to keep the pipeline flowing.

**Pull request merged**
